### ISSUE TITLE
Indirect dependency on regex

### ISSUE THREAD

**Issue by davidgraeff** [seanmonstar/pretty-env-logger#28]
Thanks for this crate!

You are currently using `env_logger` with default features. This includes the regex crate with default features which adds about 1.3MB to a binaries size (see https://github.com/rust-lang/regex/pull/613).

Could you maybe add (and proxy) the features of `env_logger` so that a consumer of your crate can disable the default features (ie "regex")?

Something along the lines of the following would help:
```toml
[features]
default = ["termcolor", "atty", "humantime", "regex"]
termcolor = ["env_logger/termcolor"]
atty = ["env_logger/atty"]
humantime = ["env_logger/humantime"]
regex = ["env_logger/regex"]
```
